# Generated by Django 5.2 on 2025-08-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal_cents',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_cents',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_cents',
        ),
    ]
