# Generated by Django 5.2.5 on 2025-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_options_remove_order_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_view_kitchen', 'Can view kitchen board'), ('can_manage_delivery', 'Can mark delivered / no-show'), ('can_view_orders', 'Can view daily orders list')], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('picked_up', 'Retirado'), ('no_show', 'Não compareceu'), ('canceled', 'Cancelado')], default='pending', max_length=12, verbose_name='Status'),
        ),
    ]
