# Generated by Django 5.2.5 on 2025-09-18 19:30

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_day',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Dia de atendimento'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'service_day'), name='one_order_per_student_per_service_day'),
        ),
    ]
