# Generated by Django 5.2.5 on 2025-09-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_service_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersExport',
            fields=[
            ],
            options={
                'verbose_name': 'Listagem',
                'verbose_name_plural': 'Listagem',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
