# Generated by Django 5.2.5 on 2025-09-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordersexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_token',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Token opaco para retirada no balcão (EAN-13, sem PII).', max_length=13, null=True, unique=True, verbose_name='Token de retirada'),
        ),
    ]
