# Generated by Django 5.2.6 on 2025-09-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_backfill_pickup_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdersExport',
        ),
    ]
