# Generated by Django 5.2.5 on 2025-08-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
