# Generated by Django 5.2.5 on 2025-09-10 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_lunch_days_override_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_source',
            field=models.CharField(blank=True, choices=[('manual', 'manual'), ('auto', 'auto')], max_length=10, verbose_name='Origem do bloqueio'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do bloqueio'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_made', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado por'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo do bloqueio'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Bloqueado para pedir'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_no_show_at',
            field=models.DateField(blank=True, null=True, verbose_name='Última falta'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_pickup_at',
            field=models.DateField(blank=True, null=True, verbose_name='Última retirada'),
        ),
        migrations.AddField(
            model_name='user',
            name='no_show_streak',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Faltas consecutivas'),
        ),
        migrations.CreateModel(
            name='BlockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('block', 'block'), ('unblock', 'unblock')], max_length=8, verbose_name='Ação')),
                ('source', models.CharField(choices=[('manual', 'manual'), ('auto', 'auto')], max_length=8, verbose_name='Origem')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_events_made', to=settings.AUTH_USER_MODEL, verbose_name='Executado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de bloqueio',
                'verbose_name_plural': 'Eventos de bloqueio',
                'ordering': ('-created_at',),
            },
        ),
    ]
