# Generated by Django 5.2.5 on 2025-09-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_block_source_user_blocked_at_user_blocked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Se marcado, ao autenticar o usuário será redirecionado para definir uma nova senha.', verbose_name='Deve trocar a senha no próximo login'),
        ),
    ]
