# Generated by Django 5.2.5 on 2025-09-02 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Aluno', 'is_staff': False}, related_name='student_classes', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
    ]
