# Generated by Django 5.2.5 on 2025-09-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_studentclass_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='days_mask',
            field=models.PositiveSmallIntegerField(default=31, help_text='Weekdays this class receives lunch (Mon–Sun). Applies to all students without an individual override.'),
        ),
    ]
