# Generated by Django 5.2.5 on 2025-09-22 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_studentclass_days_mask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='academic_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ex.: 2025. Usado para relatórios e filtros.', null=True, verbose_name='Academic year'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para arquivar esta turma (permanece visível em relatórios).', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='successor',
            field=models.ForeignKey(blank=True, help_text='Turma correspondente do próximo ano/nível.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessors', to='classes.studentclass', verbose_name='Next-year class'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='days_mask',
            field=models.PositiveSmallIntegerField(default=31, help_text='Dias da semana em que a turma recebe almoço (Seg–Dom). Aplicado a todos os estudantes sem sobrescrita individual.'),
        ),
        migrations.AddIndex(
            model_name='studentclass',
            index=models.Index(fields=['is_active'], name='classes_stu_is_acti_dd54e2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclass',
            index=models.Index(fields=['academic_year'], name='classes_stu_academi_514c9d_idx'),
        ),
    ]
