# Generated by Django 5.2.5 on 2025-09-22 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_studentclass_academic_year_studentclass_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='prev_year',
            field=models.OneToOneField(blank=True, help_text='Turma correspondente do ano anterior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_year', to='classes.studentclass', verbose_name='Previous-year class'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='successor',
            field=models.ForeignKey(blank=True, help_text='Ponte legada para a turma do próximo ano/nível.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessors', to='classes.studentclass', verbose_name='Next-year class (legacy)'),
        ),
        migrations.AddIndex(
            model_name='studentclass',
            index=models.Index(fields=['year'], name='classes_stu_year_19745b_idx'),
        ),
    ]
