# Generated by Django 5.2.6 on 2025-09-30 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_studentclass_prev_year_studentclass_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'ordering': ('name',), 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='academic_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ex.: 2025. Usado para relatórios e filtros.', null=True, verbose_name='Ano acadêmico'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para arquivar esta turma (permanece visível em relatórios).', verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Aluno', 'is_staff': False}, related_name='student_classes', to=settings.AUTH_USER_MODEL, verbose_name='Alunos'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='prev_year',
            field=models.OneToOneField(blank=True, help_text='Turma correspondente do ano anterior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_year', to='classes.studentclass', verbose_name='Turma do ano anterior'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='successor',
            field=models.ForeignKey(blank=True, help_text='Ponte legada para a turma do próximo ano/nível.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessors', to='classes.studentclass', verbose_name='Turma do próximo ano (legacy)'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Ano'),
        ),
    ]
