# Generated by Django 5.2.5 on 2025-10-02 14:14

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_studentclass_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AddConstraint(
            model_name='studentclass',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('year'), name='uniq_studentclass_name_year_ci'),
        ),
    ]
