# Generated by Django 5.2.5 on 2025-10-31 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_studentclass_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraLunchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data extra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_lunch_days', to='classes.studentclass', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Dia extra de almoço',
                'verbose_name_plural': 'Dias extras de almoço',
                'ordering': ['date'],
                'permissions': [('can_manage_extra_days', 'Pode gerenciar dias extras de almoço')],
                'unique_together': {('student_class', 'date')},
            },
        ),
    ]
