# Generated by Django 5.2.5 on 2025-09-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('rotulo', models.CharField(max_length=120, verbose_name='Rótulo')),
                ('repete_anualmente', models.BooleanField(default=False, help_text='Ex.: 25/12 todo ano.', verbose_name='Repete anualmente')),
            ],
            options={
                'verbose_name': 'Dia sem atendimento',
                'verbose_name_plural': 'Dias sem atendimento',
                'ordering': ('data',),
            },
        ),
    ]
