# Generated by Django 5.2.5 on 2025-10-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCutoffSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_time', models.TimeField(blank=True, default=None, help_text='Horário limite diário (hora local). Ex.: 15:00', null=True)),
            ],
            options={
                'verbose_name': 'Horário limite',
                'verbose_name_plural': 'Horário limite',
            },
        ),
    ]
